services:
  db-user:
    container_name: user-storage
    image: mysql/mysql-server:8.0
    env_file: .env
    ports: ['3306:3306']
    expose: [3306]
    volumes:
      - ./User/initdb:/docker-entrypoint-initdb.d
  svc-user:
    container_name: user-service
    build: ./User
    env_file: .env
    environment:
      - MYSQL_HOST=db-user
    ports: ['4001:4001']
    expose: [4001]
    depends_on:
      - db-user
    
