const Status = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  INTERNAL_SERVER_ERROR: 500,
};

const TIMEOUT = 30000; // 30 seconds
const MAX_CONNECTION_ATTEMPTS = 10;
const CONNECTION_INTERVAL = 5000; // 5 seconds

module.exports = {
  Status,
  TIMEOUT,
  MAX_CONNECTION_ATTEMPTS,
  CONNECTION_INTERVAL,
};
