const Status = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  INTERNAL_SERVER_ERROR: 500,
};

const Complexity = {
  EASY: 'Easy',
  MEDIUM: 'Medium',
  HARD: 'Hard',
};

const Language = {
  PYTHON: 'Python',
  JAVA: 'Java',
  CPP: 'C++',
};

const Event = {
  JOIN_ROOM: 'join-room',
  LEAVE_ROOM: 'leave-room',
  Question: {
    QUESTION_CHANGE: 'question-change',
    QUESTION_UPDATE: 'question-update',
  },
  Collaboration: {
    CODE_CHANGE: 'code-change',
    CODE_UPDATE: 'code-update',
    LANGUAGE_CHANGE: 'language-change',
    LANGUAGE_UPDATE: 'language-update',
  },
  Communication: {
    CHAT_SEND: 'chat-send',
    CHAT_RECEIVE: 'chat-receive',
  },
};

const Topics = {
  ALL: 'All',
  ARRAY: 'Array',
  BACKTRACKING: 'Backtracking',
  BINARY_SEARCH: 'Binary Search',
  BINARY_SEARCH_TREE: 'Binary Search Tree',
  BINARY_TREE: 'Binary Tree',
  BINARY_INDEXED_TREE: 'Binary Indexed Tree',
  BIT_MANIPULATION: 'Bit Manipulation',
  BITMASK: 'Bitmask',
  BREADTH_FIRST_SEARCH: 'Breadth-First Search',
  BRAINTASER: 'Brainteaser',
  BUCKET_SORT: 'Bucket Sort',
  COMBINATORICS: 'Combinatorics',
  CONCURRENCY: 'Concurrency',
  COUNTING: 'Counting',
  COUNTING_SORT: 'Counting Sort',
  DATA_STREAM: 'Data Stream',
  DATABASE: 'Database',
  DEPTH_FIRST_SEARCH: 'Depth-First Search',
  DESIGN: 'Design',
  DIVIDE_AND_CONQUER: 'Divide and Conquer',
  DOUBLY_LINKED_LIST: 'Doubly-Linked List',
  DYNAMIC_PROGRAMMING: 'Dynamic Programming',
  EULERIAN_CIRCUIT: 'Eulerian Circuit',
  GAME_THEORY: 'Game Theory',
  GEOMETRY: 'Geometry',
  GRAPH: 'Graph',
  GREEDY: 'Greedy',
  HASH_FUNCTION: 'Hash Function',
  HASH_TABLE: 'Hash Table',
  HEAP_PRIORITY_QUEUE: 'Heap (Priority Queue)',
  INTERACTIVE: 'Interactive',
  ITERATOR: 'Iterator',
  LINE_SWEEP: 'Line Sweep',
  LINKED_LIST: 'Linked List',
  MATH: 'Math',
  MATRIX: 'Matrix',
  MEMOIZATION: 'Memoization',
  MERGE_SORT: 'Merge Sort',
  MINIMUM_SPANNING_TREE: 'Minimum Spanning Tree',
  MONOTONIC_QUEUE: 'Monotonic Queue',
  MONOTONIC_STACK: 'Monotonic Stack',
  NUMBER_THEORY: 'Number Theory',
  ORDERED_SET: 'Ordered Set',
  PREFIX_SUM: 'Prefix Sum',
  PROBABILITY_AND_STATISTICS: 'Probability and Statistics',
  QUEUE: 'Queue',
  QUICKSELECT: 'Quickselect',
  RADIX_SORT: 'Radix Sort',
  RANDOMIZED: 'Randomized',
  RECURSION: 'Recursion',
  REJECTION_SAMPLING: 'Rejection Sampling',
  RESERVOIR_SAMPLING: 'Reservoir Sampling',
  ROLLING_HASH: 'Rolling Hash',
  SEGMENT_TREE: 'Segment Tree',
  SHELL: 'Shell',
  SHORTEST_PATH: 'Shortest Path',
  SIMULATION: 'Simulation',
  SLIDING_WINDOW: 'Sliding Window',
  SORTING: 'Sorting',
  STACK: 'Stack',
  STRING: 'String', 
  STRING_MATCHING: 'String Matching',
  STRONGLY_CONNECTED_COMPONENT: 'Strongly Connected Component',
  TOPOLOGICAL_SORT: 'Topological Sort',
  TREE: 'Tree',
  TRIE: 'Trie',
  TWO_POINTERS: 'Two Pointers',
  UNION_FIND: 'Union Find',
};

module.exports = {
  Status,
  Complexity,
  Language,
  Event,
  Topics,
};
