name: CI Pipeline

on: 
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      # May need to setup MySQL Server also
      # https://github.com/marketplace/actions/setup-mysql

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
        with: 
          mongodb-version: '6.0'
      
      - name: Install dependencies
        run: npm ci

      # TODO: do something meaningful; such as running tests

      #- name: Run Tests
      #  run: npm run test-ci
      